#2 Write a NumPy program to get help on the add function.

#add(x1, x2[, out])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).

Returns
-------
add : ndarray or scalar
    The sum of `x1` and `x2`, element-wise.  Returns a scalar if
    both  `x1` and `x2` are scalars.

Notes
-----
Equivalent to `x1` + `x2` in terms of array broadcasting.

In [2]:
import numpy as np
print(np.add(2,3))

5


#12. Write a NuqmPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

In [3]:
a=np.array([1,7,13,105])
print(a.size)
print(a.itemsize)
print(a.size*a.itemsize)

4
4
16


#22. Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

In [42]:
b=np.array([x for x in range(1,21)])
b[8:15]=-b[8:15]
print(b)

[  1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17  18
  19  20]


#32. Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.

In [5]:
def numpyCalc(a):
    print("요소의 합 = ",end="")
    print(a.sum())
    print("행의 합 = ",end="")
    print(a.sum(axis=1))
    print("열의 합 = ",end="")
    print(a.sum(axis=0))

print(np.array([1,2,3,4,5,6,7,8,9,10]).reshape(2,5))
numpyCalc(np.array([1,2,3,4,5,6,7,8,9,10]).reshape(2,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
요소의 합 = 55
행의 합 = [15 40]
열의 합 = [ 7  9 11 13 15]


#42. Write a NumPy program to add elements in a matrix. If an element in the matrix is 0, we will not add the element below this element.

In [6]:
def arrayAdd(arr,num):
    if arr.size!=0 and arr[-1]!=0:
        arr=np.append(arr,np.array(num))
    elif arr.size==0:
        arr=np.append(arr,np.array(num))
    return arr
ar=np.array([])
ar=arrayAdd(ar,1)
ar=arrayAdd(ar,2)
ar=arrayAdd(ar,3)
ar=arrayAdd(ar,4)
ar=arrayAdd(ar,0)
ar=arrayAdd(ar,5)
print(ar)


[1. 2. 3. 4. 0.]


#52. Write a NumPy program to sort a given array by row and column in ascending order.

In [11]:
import numpy as np
a=np.array([np.random.randint(51,size=50)]).reshape(5,10)
print(a)
print("원본")
print(np.sort(a,axis=1))
print("행정렬 (오름차순)")
print(np.sort(a,axis=0))
print("열정렬 (오름차순)")

[[39  1 15 47 45 35  4 45  2  0]
 [34 36 45 48 22 13 47  6 17 14]
 [ 4 32  5 33 15 43 11 40 16 26]
 [50  1 38 29 50  0 36 31 37  2]
 [34 45 47 33 20 44 37 32 29 24]]
원본
[[ 0  1  2  4 15 35 39 45 45 47]
 [ 6 13 14 17 22 34 36 45 47 48]
 [ 4  5 11 15 16 26 32 33 40 43]
 [ 0  1  2 29 31 36 37 38 50 50]
 [20 24 29 32 33 34 37 44 45 47]]
행정렬 (오름차순)
[[ 4  1  5 29 15  0  4  6  2  0]
 [34  1 15 33 20 13 11 31 16  2]
 [34 32 38 33 22 35 36 32 17 14]
 [39 36 45 47 45 43 37 40 29 24]
 [50 45 47 48 50 44 47 45 37 26]]
열정렬 (오름차순)
