#2 Write a NumPy program to get help on the add function.

#add(x1, x2[, out])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).

Returns
-------
add : ndarray or scalar
    The sum of `x1` and `x2`, element-wise.  Returns a scalar if
    both  `x1` and `x2` are scalars.

Notes
-----
Equivalent to `x1` + `x2` in terms of array broadcasting.

In [1]:
import numpy as np
print(np.add(2,3))

5


#12. Write a NuqmPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

In [3]:
a=np.array([1,7,13,105])
print(a.size)
print(a.itemsize)
print(a.size*a.itemsize)

4
4
16


#22. Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

In [42]:
b=np.array([x for x in range(1,21)])
b[8:15]=-b[8:15]
print(b)

[  1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17  18
  19  20]


#32. Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.

In [26]:
def numpyCalc(a):
    print("요소의 합 = ",end="")
    print(a.sum())
    print("행의 합 = ",end="")
    print(a.sum(axis=1))
    print("열의 합 = ",end="")
    print(a.sum(axis=0))

print(np.array([1,2,3,4,5,6,7,8,9,10]).reshape(2,5))
numpyCalc(np.array([1,2,3,4,5,6,7,8,9,10]).reshape(2,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
요소의 합 = 55
행의 합 = [15 40]
열의 합 = [ 7  9 11 13 15]


#42. Write a NumPy program to add elements in a matrix. If an element in the matrix is 0, we will not add the element below this element.

In [18]:
def arrayAdd(arr,num):
    if arr.size!=0 and arr[-1]!=0:
        arr=np.append(arr,np.array(num))
    elif arr.size==0:
        arr=np.append(arr,np.array(num))
    return arr
ar=np.array([])
ar=arrayAdd(ar,1)
ar=arrayAdd(ar,2)
ar=arrayAdd(ar,3)
ar=arrayAdd(ar,4)
ar=arrayAdd(ar,0)
ar=arrayAdd(ar,5)
print(ar)


0
[1. 2. 3. 4. 0.]


#52. Write a NumPy program to sort a given array by row and column in ascending order.

In [44]:
a=np.array([50-x for x in range (1,51)]).reshape(5,10)
print(a)
print("원본")
print(np.sort(a,axis=1))
print("행정렬 (오름차순)")
print(np.sort(a,axis=0))
print("열정렬 (오름차순)")

[[49 48 47 46 45 44 43 42 41 40]
 [39 38 37 36 35 34 33 32 31 30]
 [29 28 27 26 25 24 23 22 21 20]
 [19 18 17 16 15 14 13 12 11 10]
 [ 9  8  7  6  5  4  3  2  1  0]]
원본
[[40 41 42 43 44 45 46 47 48 49]
 [30 31 32 33 34 35 36 37 38 39]
 [20 21 22 23 24 25 26 27 28 29]
 [10 11 12 13 14 15 16 17 18 19]
 [ 0  1  2  3  4  5  6  7  8  9]]
행정렬 (오름차순)
[[ 9  8  7  6  5  4  3  2  1  0]
 [19 18 17 16 15 14 13 12 11 10]
 [29 28 27 26 25 24 23 22 21 20]
 [39 38 37 36 35 34 33 32 31 30]
 [49 48 47 46 45 44 43 42 41 40]]
열정렬 (오름차순)
